name: rl-project
channels:
  - conda-forge
  - defaults

dependencies:
  # Intended primarily for Linux/WSL.
  # Native Windows + placo/lerobot kinematics is not reliable
  - python=3.12

  - numpy
  - scipy
  - pandas
  - matplotlib

  - pillow
  - scikit-image
  - imageio
  - imageio-ffmpeg
  - ffmpeg
  - evdev

  - control
  - gymnasium

  - pyyaml
  - python-dotenv
  - pydantic
  - tqdm
  - jupyterlab

  - pip
  - pip:
      - "lerobot[placo-dep,feetech,aloha,pusht]"
      - openai
      - google-genai
      - opencv-python
      - wandb
      - rich
      - meshcat
